In [1]:
import numpy as np
from scripts.matrix_utils import compute_q_pi

# Scenario 1

Consider a simplified example of Futsal, which is a game of European football played on a smaller court with five player teams.  Denote the players as A, B, C, D, E.  An augmented passing matrix could be as follows

\begin{equation}
P = \left[
\begin{array}{cc}
\left(\begin{array}{ccccc}
0    & 0.40 & 0.25 & 0.20 & 0.10 \\
0.15 & 0    & 0.34 & 0.25 & 0.10 \\
0.05 & 0.15 & 0    & 0.20 & 0.30 \\
0.05 & 0.15 & 0.20 & 0    & 0.20 \\
0    & 0.05 & 0.25 & 0.25 & 0    \\
\end{array}\right) & 
\begin{array}{cc}
0    & 0.05 \\
0.01 & 0.15 \\
0.05 & 0.25 \\
0.10 & 0.20 \\
0.15 & 0.30 \\
\end{array} \\
\begin{array}{cccccccccc}
\hspace{7pt}0\hspace{7pt}&\hspace{7pt} 0 \hspace{7pt}   &\hspace{7pt} 0\hspace{7pt}    &\hspace{7pt} 0\hspace{7pt}    &\hspace{7pt} 0 \hspace{7pt}   \\
\hspace{7pt}0\hspace{7pt}&\hspace{7pt} 0 \hspace{7pt}   &\hspace{7pt} 0\hspace{7pt}    &\hspace{7pt} 0\hspace{7pt}    &\hspace{7pt} 0 \hspace{7pt}   \\
\end{array} & 
\begin{array}{cc}
\hspace{7pt}1\hspace{7pt}    &\hspace{7pt} 0 \hspace{7pt}   \\
\hspace{7pt}0\hspace{7pt}    &\hspace{7pt} 1  \hspace{7pt}  \\
\end{array}
\end{array}
\right]
\end{equation}

where the upper $5 \times 5$ block is according to the passing matrix.  For example, the first row corresponds to the goalkeeper (A), who has respective probabilities 0.4, 0.25, 0.2, and 0.1 of passing to players B, C, D, E.  The goalkeeper has probability 0 to directly transfer ball possession to the $S$ state (6th column), and has probability 0.05 of making an unsuccessful pass or turnover.  Note that each row sum is 1.  The rows are presented in order of field position, so player B is a defender, players C and D are wing playmakers, and player E is the primary scorer.  Note that the probability of leaving state $S$ is 0, and the same is true for state $U$ (missed passes and/or turnovers), since the team possession ends when the ball reaches that state.  Additionally, let the probability that any given team possession begins with a player be given by initial distribution

\begin{equation}
\alpha = (0.35, 0.26, 0.17, 0.17, 0.05).
\end{equation}

For example, player $B$ begins a team possession with probability 0.26, which could be due to pass interceptions, steals, recoveries, etc.  Denote respectively for players $A, \ldots, E$ as $q_1, \ldots, q_5$, recalling that $q_j$ is the probability that player $j$ is involved in a team possession that ends in state $S$.  

In [2]:
P = np.array([
    [0.00, 0.40, 0.25, 0.20, 0.10, 0.00, 0.05],
    [0.15, 0.00, 0.34, 0.25, 0.10, 0.01, 0.15],
    [0.05, 0.15, 0.00, 0.20, 0.30, 0.05, 0.25],
    [0.05, 0.15, 0.20, 0.00, 0.20, 0.10, 0.20],
    [0.00, 0.05, 0.25, 0.25, 0.00, 0.15, 0.30],
    [0.00, 0.00, 0.00, 0.00, 0.00, 1.00, 0.00],
    [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.00]
])

alpha = np.array([0.35, 0.26, 0.17, 0.17, 0.05])

print(P)
print(alpha)




[[0.   0.4  0.25 0.2  0.1  0.   0.05]
 [0.15 0.   0.34 0.25 0.1  0.01 0.15]
 [0.05 0.15 0.   0.2  0.3  0.05 0.25]
 [0.05 0.15 0.2  0.   0.2  0.1  0.2 ]
 [0.   0.05 0.25 0.25 0.   0.15 0.3 ]
 [0.   0.   0.   0.   0.   1.   0.  ]
 [0.   0.   0.   0.   0.   0.   1.  ]]
[0.35 0.26 0.17 0.17 0.05]


# Scenario 1

In [3]:
# Compute q and pi
q, pi = compute_q_pi(P, alpha)

# Display the results
print("Vector q:")
for j, q_val in enumerate(q):
    print(f"q_{j} = {q_val:.4f}")

print("\nVector pi:")
for j, pi_val in enumerate(pi):
    print(f"pi_{j} = {pi_val:.4f}")


Vector q:
q_0 = 0.4445
q_1 = 0.5177
q_2 = 0.6127
q_3 = 0.6387
q_4 = 0.5785

Vector pi:
pi_0 = 0.1592
pi_1 = 0.1854
pi_2 = 0.2194
pi_3 = 0.2287
pi_4 = 0.2072


# Scenario 2

Changes $p_{5,S}=0.25$ from $0.15$ and $p_{5,U}=0.2$ from $0.3$, making player E much more successful at scoring.

In [4]:
# Python begins indices at 0, so we need to adjust by 1.
P_2 = np.copy(P)
P_2[4,5] = 0.25  # from 0.15
P_2[4,6] = 0.20  # from 0.3

print(P_2)

# Compute q and pi
q_2, pi_2 = compute_q_pi(P_2, alpha)

# Display the results
print("Vector q:")
for j, q_val in enumerate(q_2):
    print(f"q_{j} = {q_val:.4f}")

print("\nVector pi:")
for j, pi_val in enumerate(pi_2):
    print(f"pi_{j} = {pi_val:.4f}")

[[0.   0.4  0.25 0.2  0.1  0.   0.05]
 [0.15 0.   0.34 0.25 0.1  0.01 0.15]
 [0.05 0.15 0.   0.2  0.3  0.05 0.25]
 [0.05 0.15 0.2  0.   0.2  0.1  0.2 ]
 [0.   0.05 0.25 0.25 0.   0.25 0.2 ]
 [0.   0.   0.   0.   0.   1.   0.  ]
 [0.   0.   0.   0.   0.   0.   1.  ]]
Vector q:
q_0 = 0.4469
q_1 = 0.5151
q_2 = 0.6114
q_3 = 0.6043
q_4 = 0.6687

Vector pi:
pi_0 = 0.1570
pi_1 = 0.1810
pi_2 = 0.2148
pi_3 = 0.2123
pi_4 = 0.2349


# Scenario 3

Changing $\alpha = (0.3, 0.45, 0.10, 0.10, 0.05)$, making the defender player $B$ begin possessions more often (true for defensive players), and in turn, lowering the initial possession probabilities for $A$, $C, D,$ and $E$.

In [5]:
alpha_3 = np.array([0.30, 0.45, 0.10, 0.10, 0.05])

# Compute q and pi
q_3, pi_3 = compute_q_pi(P, alpha_3)

# Display the results
print("Vector q:")
for j, q_val in enumerate(q_3):
    print(f"q_{j} = {q_val:.4f}")

print("\nVector pi:")
for j, pi_val in enumerate(pi_3):
    print(f"pi_{j} = {pi_val:.4f}")

Vector q:
q_0 = 0.4296
q_1 = 0.6444
q_2 = 0.6040
q_3 = 0.6181
q_4 = 0.5870

Vector pi:
pi_0 = 0.1490
pi_1 = 0.2235
pi_2 = 0.2095
pi_3 = 0.2144
pi_4 = 0.2036
